### ISSUE TITLE
create png

### ISSUE THREAD

**Issue by mariusel09** [Zverik/bigmap2#11]
how can i create a png file from a selected area in open street map?,step by step please

**Comment by mariusel09** [comment]
with bigmap 2

**Comment by Zverik** [comment]
See here: https://wiki.openstreetmap.org/wiki/Bigmap

**Comment by mariusel09** [comment]
i already saw that but i don t know.i downloaded with map extension,wld or py but i want a pang image of map in my pc.a little help please?

**Comment by mariusel09** [comment]
png

**Comment by Zverik** [comment]
Choose an area and click "Enqueue" (it should not be too big: I recon the limit is 12x12). Then wait a minute or two, and you'll get your map.
