### ISSUE TITLE
generated perl & python.  Exits on first tile

### ISSUE THREAD

**Issue by harry-wood** [Zverik/bigmap2#4]
The perl & python generated script downloads. Neither of them worked for me. They both seemed to exit on the first iteration of the loop, downloading just one tile. no error message

I'll look it a bit more at some point. I was just briefly trying it out prepping for a HOT Nepal blog post

**Comment by Zverik** [comment]
That's strange, I use bigmap2-generated scripts all the time. Could you please specify for which layers were your scripts generated?

**Comment by harry-wood** [comment]
It's OK. It was just me running wget wrongly

`wget http://bigmap.osmz.ru/bigmap.php?action=perl&xmin=12073&xmax=12076&ymin=6878&ymax=6880&zoom=14&scale=256&tiles=mapnik`

instead of

`wget "http://bigmap.osmz.ru/bigmap.php?action=perl&xmin=12073&xmax=12076&ymin=6878&ymax=6880&zoom=14&scale=256&tiles=mapnik"`

seemed to work but with all the variables to zero
