### ISSUE TITLE
Layer OpenmapSurfer has new URL, and MapquestOpen is no longer free available

### ISSUE THREAD

**Issue by stephan75** [Zverik/bigmap2#8]
Hello Ilya,

IIRC, the OpenMapSurfer Tiles have a new URL path,

and the Mapquest Open Tiles are no longer available for free.

Is it big effort to adjust the layer chooser menu of bigmap2 service?

**Comment by stephan75** [comment]
Hello @Zverik ... any chance of progress about those layers?

**Comment by Zverik** [comment]
Just done, thanks.
